baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'NeuralSight'

# Change the default theme
theme = "hugo-theme-learn"
# For search functionality
[outputs]
home = [ "HTML", "RSS", "JSON"]

[params]
# Change default color scheme with a variant one. Can be "red", "blue", "green".
themeVariant = "custom"

publishDir = "docs"